# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Sets up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install Depencencies
      run: npm install 
    - name: Install Playwright
      run: npx playwright install
    - name: Start Front-End
      run: npm run start &
    - name: Start Back-End
      run: npm run server &
    - name: Run Tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Deploying Front-End
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FRONT_END }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
      - name : Deploying Back-End
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BACK_END }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          
