
name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Start Frontend
      run: npm run start:fe &
    - name: Start Backend 
      run : npm run start:be &
    - name: Install Playwright browsers
      run: npx playwright install 
    - name: Execute UI Tests
      run: npm run tests:ui
